### ISSUE TITLE
Header description text size

### ISSUE THREAD

**Issue by craigbarowsky** [DCActionforChildren/dcaction#110]
-Improve the ability to view the map by decreasing font size of  header text ("Where resources and well-being vary in DC") and the description text below it.

**Comment by craigbarowsky** [comment]
I played around with the browser inspector and sent the attached layout to @shanab202 which she was fine with.  The changes I made were:
Header - change to 30px
Intro font size - change to 1.0em

Here's a screenshot of the comp - https://drive.google.com/a/datakind.org/file/d/0B7gRVZRW1ArtVFZocGVybnNKYzg/view?usp=sharing

**Comment by nickmcclellan** [comment]
So I'm having a couple of issues with this:
1. The data in the data store is not as updated at the current JSON information. For one, it lacks the Lat/Lon information, so converting it to a JSON will not plot it onto the map. Second, it also lacks the graduation rate.
2. I was going to try to join what information I had from the CSV files I used to make the original JSON files, but the DCPS school lack a joining code. I can try to bridge it later tonight, but I don't think I can do it before 5 p.m. I went ahead and added to original CSV files so you can see what I mean.

My suggestion is that @shanab202 take a look at the schools.csv and charters.csv sheets I added to the data store and identify any areas that need updating. It will be a lot easier to set those to functioning JSONs than getting the Data Store up and running.

Ideally, we could request Lat/Lon from the same place we got the Data Store information and fill in this information from scratch rather than reaching back to what's in the data tool already. I set up the Data Store as a tool for collecting the latest data from DC government related to schools. It's designed to key off of the joining code so the latest information can be appended in new columns. Then we can export spreadsheets with the necessary information for the data tool.

Take a look and let me know what you think.

**Comment by shanab202** [comment]
Thanks for the heads up @nickmcclellan. I will work on this tomorrow at the office. Thanks for getting this all done today.
