### ISSUE TITLE
Adjust filtering of the map so that anything with zeros shows up as grey

### ISSUE THREAD

**Issue by craigbarowsky** [DCActionforChildren/dcaction#112]

**Comment by pdarche** [comment]
@akilism's commit fixed this issue.  @shanab202, please check out the map and reopen the issue if there are any problems!

**Comment by shanab202** [comment]
@pdarche  @akilism the commit fixed the issue. Thanks so much! Is there a quick way to fix the map legend? Using libraries as an example, the layer now shades in regions where there are 1 and above, but the map legend includes "1 and above" and "less than 1." Anything with less than 1 is now grey, so it's just a bit confusing.
This is NOT a huge priority since the more critical fix is done, but just something to flag as we try to clean up the tool.

**Comment by akilism** [comment]
Hi

Sorry didnt notice the legend was off in some circumstances... I'll take a
look at it tonight.

-Akil

**Comment by shanab202** [comment]
Thanks so much @akilism
