### ISSUE TITLE
fix population totals in call-out box

### ISSUE THREAD

**Issue by ajschumacher** [DCActionforChildren/dcaction#127]
as reported by @shanab202 in email:

> So I just loaded the changes and everything looks good except for one thing—when the Tool first opens, the callout box does not contain updated values. All the individual neighborhoods appear correct, but the total values for the city are from the 2012 ACS. Is there a way to fix this quickly? **Population total should be 619,371 and under 18 population is 105,291**.

(emphasis added)

Josh De La Rosa suspects that "It could be the the city level statistics are hard coded in different part of the program". @nickmcclellan, maybe you know?

**Comment by ajschumacher** [comment]
from @jotok:

> It looks like the summary numbers are indeed hardcoded into index.html and index2.html: https://github.com/DCActionforChildren/dcaction/search?utf8=%E2%9C%93&q=605%2C759
> 
> Can someone just create the totals by opening neighbohoods.csv in Excel and adding up the appropriate columns?

**Comment by ajschumacher** [comment]
from Josh De La Rosa:

> Some of the variables are rates derived.  Simply summing doesn't work.
> 
> I think we should hold off until we can folk the Tract program and summarize at the state level.
> 
> This will ensure the micro cluster numbers = the macro state numbers.

**Comment by ajschumacher** [comment]
For complete deep context, the original email from Nick to Josh De La Rosa and the response:

_from Nick to Josh:_

"""
Hey Josh,

I have a request that I hope won’t be too difficult. I’ve been chatting with some of the new volunteers about the visualization and Margo, a volunteer who is helping us chart the ethnicity variables, and she pointed out it might be cool to have the graphic display D.C. wide information on the initial load.

I was wondering if you could queue these variables easily for the city. It’s only a handful, the few that we visualize in the sidebar. It’s not every variable we’ve plotted for each variable. Here’s all I’m looking for:

Population total
Population under 18
Single mother families
Children in poverty

Ethnicity variables (these we took from the 2010 Census, so for consistency they should probably stay the same)
NonHispanic White (total)
NonHispanic Black (total)
NonHispanic Other (total)
Hispanic (total)
NonHispanic White (under 18)
NonHispanic Black (under 18)
NonHispanic Other (under 18)
Hispanic (under 18)

Do you think you could grab these for me? I figure it might not be too difficult for you since you’ve been in all of the variable codes. You can just email me the numbers if you can grab them.

Thanks!

Nick
"""

_from Josh to Nick:_

"""
Population total     605,759
Population under 18  103,986
Single mother families   0.48215000
Children in poverty  0.28873246

Ethnicity variables 
NonHispanic White (total)    209,183
NonHispanic Black (total)    305,141
NonHispanic Other (total)    35,176
Hispanic (total)     56,259
NonHispanic White (under 18)     18,487
NonHispanic Black (under 18)     68,260
NonHispanic Other (under 18)     4,372
Hispanic (under 18)  12,867 

This is all 2012 data
"""

**Comment by joshdelarosa1** [comment]
This seems related to #121 

Should I close #121?

**Comment by ajschumacher** [comment]
ah! you're right; I hadn't seen #121. I'll get it.

**Comment by joshdelarosa1** [comment]
<body lang=EN-US link=blue vlink=purple style='tab-interval:.5in'>

<div class=WordSection1>
<p class=MsoNormal>The <i style='mso-bidi-font-style:normal'>requirement</i> is
that the city total matches the cluster totals (plus or minus a few do to
rounding after and cross walking tracts to blocks).</p>
<p class=MsoNormal>Instead of calculating the sums manually, my suggested <i
style='mso-bidi-font-style:normal'>solution</i> is to:</p>
<p class=MsoListParagraphCxSpFirst style='text-indent:-.25in;mso-list:l0 level1 lfo1'><![if !supportLists]><span
style='font-family:Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:
Symbol'><span style='mso-list:Ignore'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>Make a spin off of <a
href="https://github.com/DCActionforChildren/dcaction/blob/gh-pages/data/fetch_acs.rb"><span
class=SpellE>fetch_acs.rb</span></a> for the city of DC</p>
<p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;mso-list:l0 level1 lfo1'><![if !supportLists]><span
style='font-family:Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:
Symbol'><span style='mso-list:Ignore'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>At <a
href="https://github.com/DCActionforChildren/dcaction/blob/gh-pages/data/fetch_acs.rb#L9">line
9</a>, update the geography from tract, to city ('for=state:11')</p>
<p class=MsoListParagraphCxSpLast style='text-indent:-.25in;mso-list:l0 level1 lfo1'><![if !supportLists]><span
style='font-family:Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:
Symbol'><span style='mso-list:Ignore'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>Skip most of the <a
href="https://github.com/DCActionforChildren/dcaction/blob/gh-pages/data/crosswalk.rb">cross
walking program</a>, just output as a city level CSV.</p>
<p class=MsoNormal>Then use the city level CSV to update the call out boxes.<span
style='mso-spacerun:yes'>  </span>Don’t know if it possible, but it would
awesome if we could update the call out box update as well found in <a
href="https://github.com/DCActionforChildren/dcaction/blob/gh-pages/index.html">Index</a>
and <a
href="https://github.com/DCActionforChildren/dcaction/blob/gh-pages/index2.html">Index2</a></p>
</div>

</body>

</html>

**Comment by shanab202** [comment]
Just looping back on this. Thanks for organizing @ajschumacher and @joshdelarosa1.  Any takers?

**Comment by shanab202** [comment]
Happy New Year! Hope everyone had a good holiday season. Just looping back on this-- @jotok and @mjrich, would either of you be able to help with this? or any other takers? Thanks so much! 
Here's a pic of what we're talking about: 
![datatoolfix](https://cloud.githubusercontent.com/assets/7978244/5618714/a22660a4-94e9-11e4-803d-578c9bdaeca9.JPG)

**Comment by jotok** [comment]
Moved to #142.
