### ISSUE TITLE
0 vs. 0% vs. n/a on map

### ISSUE THREAD

**Issue by bonnieok** [DCActionforChildren/dcaction#51]
Make sure when a value is blank, the map shows the neighborhood in gray, not as the lowest value of green. Also, in non-% variables, make sure the value displays as 0, not 0%.

**Comment by eschow** [comment]
Wasn't completely sure which cases should display 0 v. 0% so didn't want to close this issue. 

Did however make it so that sidebar shows N/A and polygon is default gray if value isn't available for that neighborhood. (https://github.com/nickmcclellan/dcaction/commit/888b71e862750a7f7a89cda200c007830249cd78)

**Comment by nickmcclellan** [comment]
I've looked over this and I think things are resolved. Thanks Emily, you're the best!
