### ISSUE TITLE
Issues with 'no_hs_degree_25_plus' and 'no_hs_degree_18_24' data

### ISSUE THREAD

**Issue by JyothisS** [DCActionforChildren/dcaction#67]
Based on a check of Cluster 4 and Cluster 16 in the spreadsheet https://docs.google.com/spreadsheet/ccc?key=0AliQRBwTvad9dC1reWl1NUpXVkEyUXBQOVNGNUV6dFE&usp=sharing#gid=17:

The 'no_hs_degree_25_plus' variable values are the correct values of 'no_hs_degree_18_24' variable. 

The 'no_hs_degree_18_24' variable values are incorrect. They are exceedingly high and almost equal to the total 18+ population.

**Comment by JyothisS** [comment]
How is the 'Percent 18-24 without a high school degree' on the map being calculated?

**Comment by nickmcclellan** [comment]
I am explaining in an email why we should pay little attention to the no_hs_degree_25_plus and no_hs_degree_18_24 data columns, neither show up in the graphic and they are probably a result of some code left over from a previous crosswalk. I've determined that they are not used to calculate the % 18-24 without a high school diploma data layer. I'm going to forward your second question to Josh D. and ask him to double check that variable to make sure we're AOK on it.

Thanks again Jyothis for your hard work in being a back stop on this data. This is why our work is going to be respected, we are double and triple checking it!

**Comment by nickmcclellan** [comment]
Josh replied, he's checking this formula and will let me know how things turn out by noon today, he said.

**Comment by JyothisS** [comment]
While the percentages for 'No HS degree 18 to 24' is getting corrected, what happened to the '25+ No HS degree' layer? Was there any decision on not including it?

**Comment by nickmcclellan** [comment]
I think we should hold this variable and resolve this issue after we launch. Josh followed up and he mentioned the way we need to solve this might involve editing the Ruby script, which I am hard-pressed to do this close to launch. I saw we go ahead with the youth ready-to-work variable and fix the issue related to these variables when we wrap up documentation of the Ruby process.

**Comment by jotok** [comment]
Hey Nick. I looked upthread but I didn't see any mention of the ruby script
problems. I'll ask Josh D. about it, but is that conversation already
written down somewhere?

**Comment by nickmcclellan** [comment]
Hey Josh, he replied in an email on the 24th with this:

Nick,

I think no_hs_degree_25_plus_denom HS is incorrect.  It should be either:

'no_hs_degree_25_plus_denom'
'B15001_001E'-('B15001_003E'+'B15001_044E')

or

'no_hs_degree_25_plus_denom' 
'B15001_011'+'B15001_019'+'B15001_027'+'B15001_035'+
'B15001_052'+'B15001_060'+'B15001_068'+'B15001_076'

The 18-24 formulas are correct.

I went ahead and tried the first formula but I was getting the same result as before (which I'm assuming is an error since Jyothis flagged it). But when I looked for the second variables I didn't see it in any output, which made me assume it must involve a Ruby edit.

I think part of this is my fault because I had mysteriously labeled the diploma layers with a "work" label, confusing it with the ready-to-work variable. I calculated the percentage for these variables (no_dip_18 and no_dip_25 in the neighborhoods2.csv spreadsheet) and something still seems wrong, which is why I am hesitant.

If you think we can pull out verified %'s for each neighborhood for residents 18-24 and 25+ with no diplomas, that would be great, I'd be happy to include it!

**Comment by jotok** [comment]
Thanks, I'll see if I can reproduce the 'no output' error.

Josh

**Comment by jotok** [comment]
OK, I think the problem with Josh D's second set of variables -- the ones that he says didn't produce any output -- is that he was missing the E on the end of each variable name. For example, 'B15001_011' should be 'B15001_011E'.

I ran the numbers with the second formula, but it seems to be producing the same totals that we were getting before (although the margings of error are different). Maybe leaving this until after launch is still the way to go.
