### ISSUE TITLE
Zoom to fit DC bounds on load

### ISSUE THREAD

**Issue by eschow** [DCActionforChildren/dcaction#93]
On mobile, it's not possible to see all of DC.

**Comment by nickmcclellan** [comment]
I'm able to see all of D.C. I don't think we should let this hold up the launch, I'm not able to reproduce on my iPhone. If we really want to get into mobile performance, there are a lot more issues than just the zoom min and zoom max. I'm thinking we should disable dataset selection for mobile and only allow narrative choices because there is a bit of a lag when we enable full functionality.

![2014-05-27 10 49 55](https://cloud.githubusercontent.com/assets/1339437/3093257/ab4e8884-e5b0-11e3-8ece-e73a87b18135.png)

**Comment by hyesookchung** [comment]
I played around today on my iPhone and it was much easier to navigate and read. thanks Nick.

**Comment by ajschumacher** [comment]
Relevant comment from @cmgiven in #133, copied here for convenience:

> Might want to consider dynamically setting the maxBounds, but this will only become necessary once #93 is implemented, and should be considered concurrently.

**Comment by cmgiven** [comment]
Using a bit of a hack-y solution (manually setting values based on the height of the container) rather than use `fitBounds()`, which generally zooms us too far out for our preferences.
